# fly.toml app configuration file generated for nguyenltvinh-ascension-chess on 2026-01-01T02:43:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-ascension-chess-server'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  RUST_LOG = 'info'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
